---

- block:
  - name: Link Service Unit
    file:
      src: "{{gunicorn_config_dir}}/gunicorn.service"
      dest: "{{gunicorn_systemd_service_dir}}/gunicorn.service"
      owner: root
      group: root
      state: link

  - name: Reload systemd Daemon for gunicorn changes
    systemd:
     daemon_reload: yes
    changed_when: True
    when: gunicorn_service_unit_result is changed

  - name: Enable Service
    systemd:
      name: "gunicorn.service"
      enabled: "{{gunicorn_enable_service}}"
      state: "{{gunicorn_state|default('stopped')}}"
    when: gunicorn_enable_service
  when: gunicorn_install_service
