---

- name: "start {{gunicorn_service_name}}.service"
  systemd:
    name: "{{gunicorn_service_name}}.service"
    state: started

- name: "stop {{gunicorn_service_name}}.service"
  systemd:
    name: "{{gunicorn_service_name}}.service"
    state: stopped

- name: "restart {{gunicorn_service_name}}.service"
  systemd:
    name: "{{gunicorn_service_name}}.service"
    state: restarted

- name: "reload {{gunicorn_service_name}}.service"
  systemd:
    name: "{{gunicorn_service_name}}.service"
    state: reloaded
