---

- name: "start gunicorn service"
  systemd:
    name: "gunicorn.service"
    state: started
  listen: "start application"

- name: "stop gunicorn service"
  systemd:
    name: "gunicorn.service"
    state: stopped
  listen: "stop application"

- name: "restart gunicorn service"
  systemd:
    name: "gunicorn.service"
    state: restarted
  listen: "restart application"

- name: "reload gunicorn service"
  systemd:
    name: "gunicorn.service"
    state: reloaded
  listen: "reload application"
